# Nome do workflow
name: Deploy to GitHub Pages

# Gatilhos
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

# Permissões
permissions:
  contents: write
  pages: write
  id-token: write

# Ambiente de publicação
env:
  name: github-pages

# Jobs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze > requirements.txt

      - name: Run downloads_files.py
        run: |
          python downloads_files.py
          cat downloaded_files.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Generate metadata
        run: |
          node generate_metadata.js
          cat files_metadata.json

      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist  # Apenas os arquivos de build
          exclude-assets: |
            generate_metadata.js
            downloads_files.py
            requirements.txt
            .github/workflows/*

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
